// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artist struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	URL     string `json:"url"`
	Summary string `json:"summary"`
}

type Track struct {
	Title     string  `json:"title"`
	URL       string  `json:"url"`
	Listeners int     `json:"listeners"`
	Artist    *Artist `json:"artist"`
}
